### ISSUE TITLE
Recommendation: Rename this repo/extension to ExtensibilityTemplates

### ISSUE THREAD

**Issue by yannduran** [madskristensen/ExtensibilityTemplatePack#2]
The current name is **misleading**, as it contains more than just **item templates**, and it doesn't even match the current extension name  of _Extensibility Template Pack_ either.

A better/simpler name for the repo would be _ExtensibilityTemplates_, and the extension could be simply called _Extensibility Templates_.

Whether this suggestion is deemed a good idea or not, I'd at least recommend that there be consistency between the names of the repo, the extension, and what's displayed in the marketplace.

**Comment by madskristensen** [comment]
I renamed it

**Comment by yannduran** [comment]
Shouldn't the **repo** and what's used the **README.md** also be renamed, for consistency?

I always find it quite confusing when I'm manually looking for the repo for some extension etc (as opposed to clicking on the link in the Marketplace), and it doesn't match the extension name. Sometimes there's even a mismatch between the **extension name** in the Marketplace, the **description**, the **namespace(s)** used, the **repo** name **AND** the **README.md** file. 

As developers, shouldn't we be striving for consistency? Especially when we expect others to actually use our extension/package/code. It looks sloppy otherwise!

I can do a pull request for this if you'd like me to.

**Comment by yannduran** [comment]
@madskristensen ^^

**Comment by madskristensen** [comment]
Yes, it needs to change too
